fshon sync knn baseline 
goal: build simple ml version of the idea

im leaarning:
-how to create a small data set for fashion 
-splitting data into x and y 
-training knn model
-predict outfit style
-finding similar outfits

# pandas make data looks like a table aka its called table frame
# numpy is to make data as numbers lets say 
#baggy : 1 not baggy : 0 cause it cant understand words we use numbers using numpy

In [5]:

import pandas as pd 
import numpy as np

In [6]:
columns = [
"item",
"black",
"colorful",
"baggy",
"fitted",
"sporty",
"leather",
"fur",
"modern",
"elegant",
"edgy",
"style"



]

In [7]:
data = [
    ["baggy black pants", 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, "streetwear"],
    ["baggy black hoodie", 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, "streetwear"],

    ["baggy grey pants", 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, "sporty"],
    ["baggy grey shirt", 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, "sporty"],

    ["black fancy dress", 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, "elegant"],
    ["blue fancy dress", 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, "elegant"]
]
df = pd.DataFrame(data , columns=columns)
df

,item,black,colorful,baggy,fitted,sporty,leather,fur,modern,elegant,edgy,style
0,baggy black pants,1,0,1,0,0,0,0,1,0,1,streetwear
1,baggy black hoodie,1,0,1,0,1,0,0,1,0,1,streetwear
2,baggy grey pants,0,0,1,0,1,0,0,1,0,0,sporty
3,baggy grey shirt,0,0,1,0,1,0,0,1,0,0,sporty
4,black fancy dress,1,0,0,1,0,0,0,1,1,0,elegant
5,blue fancy dress,0,1,0,1,0,0,0,1,1,0,elegant

In [8]:
features = [
    "black",
"colorful",
"baggy",
"fitted",
"sporty",
"leather",
"fur",
"modern",
"elegant",
"edgy"
]
X = df[features]
Y = df["style"]

X

   black  colorful  baggy  fitted  sporty  leather  fur  modern  elegant  edgy
0      1         0      1       0       0        0    0       1        0     1
1      1         0      1       0       1        0    0       1        0     1
2      0         0      1       0       1        0    0       1        0     0
3      0         0      1       0       1        0    0       1        0     0
4      1         0      0       1       0        0    0       1        1     0
5      0         1      0       1       0        0    0       1        1     0

In [9]:
Y

0    streetwear
1    streetwear
2        sporty
3        sporty
4       elegant
5       elegant
Name: style, dtype: object

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn = KNeighborsClassifier(n_neighbors= 1)
knn.fit(X,Y)

KNeighborsClassifier(n_neighbors=1)

In [12]:
new_outfit = [[1,0,1,0,0,1,0,1,0,1]]

prediction = knn.predict(new_outfit)

prediction

c:\Users\rahaf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['streetwear'], dtype=object)

In [13]:
new_outfit = pd.DataFrame( 
[[1,0,1,0,0,1,0,1,0,1]],

columns=features

)

prediction = knn.predict(new_outfit)

prediction

array(['streetwear'], dtype=object)

In [14]:
new_outfits = pd.DataFrame([ 
[1,0,1,0,0,1,0,1,0,1],
[0, 1, 0, 1, 0, 0, 0, 1, 1, 0],
[0, 0, 1, 0, 1, 0, 0, 1, 0, 0]
],
columns=features
)
predictions = knn.predict(new_outfit)
predictions

array(['streetwear'], dtype=object)

In [27]:
from sklearn.neighbors import NearestNeighbors

In [26]:
similarity_model = NearestNeighbors(n_neighbors=3)
similarity_model.fit(X)

NearestNeighbors(n_neighbors=3)

In [25]:
query_outfit = pd.DataFrame(

[[1,0,1,0,0,1,0,1,0,1]],
    columns=features


)
query_outfit

   black  colorful  baggy  fitted  sporty  leather  fur  modern  elegant  edgy
0      1         0      1       0       0        1    0       1        0     1

In [1]:
from sklearn.neighbors import NearestNeighbors

In [2]:
outfit_search_model = NearestNeighbors(n_neighbors= 3)

In [18]:
outfit_search_model.fit(X)

NearestNeighbors(n_neighbors=3)

In [21]:
# This is the new outfit we want to search similar outfits for
# Order: black, colorful, baggy, fitted, sporty, leather, fur, modern, elegant, edgy

query_outfit = pd.DataFrame(
    [[1, 0, 1, 0, 0, 1, 0, 1, 0, 1]],
    columns=features
)

query_outfit

   black  colorful  baggy  fitted  sporty  leather  fur  modern  elegant  edgy
0      1         0      1       0       0        1    0       1        0     1

In [22]:
# Find the nearest outfits to the query outfit

distances, indices = outfit_search_model.kneighbors(query_outfit)

distances

array([[1.        , 1.41421356, 2.        ]])

In [23]:
indices

array([[0, 1, 2]])

In [28]:
similarity_model = df.iloc[indices[0]]

similarity_model

,item,black,colorful,baggy,fitted,sporty,leather,fur,modern,elegant,edgy,style
0,baggy black pants,1,0,1,0,0,0,0,1,0,1,streetwear
1,baggy black hoodie,1,0,1,0,1,0,0,1,0,1,streetwear
2,baggy grey pants,0,0,1,0,1,0,0,1,0,0,sporty

In [35]:
similar_outfits = df.iloc[indices[0]].copy()

similar_outfits["distance"] = distances[0]

similar_outfits[["item", "style", "distance"]]

                 item       style  distance
0   baggy black pants  streetwear  1.000000
1  baggy black hoodie  streetwear  1.414214
2    baggy grey pants      sporty  2.000000

In this notebook, I built the first simple ML baseline for the F$SHN $YNC project.

### What I did

- Created a small fashion dataset manually.
- Converted outfit descriptions into numerical features.
- Used `X` to store the input features.
- Used `y` to store the target style labels.
- Trained a KNN classifier to predict outfit style.
- Tested the model on new outfits.
- Used Nearest Neighbors to find similar outfits.

### What I learned

- `DataFrame` is like a table.
- `columns` give meaning to the data values.
- `features` are the columns used by the model.
- `X` contains the input features.
- `y` contains the correct answer/label.
- `KNeighborsClassifier` predicts the style.
    KNeighborsClassifier is used to predict the outfit style, such as streetwear, elegant,sporty,fancy ..etc it predict the vibe lets say
- `NearestNeighbors` finds similar outfits.
NearestNeighbors is used to find similar outfits based on the outfit features.like is it fit or baggy?black or colorfull?..etc.

In this project, KNN predicts the vibe of the outfit, while NearestNeighbors recommends outfits that look similar to it.
- Smaller distance means the outfit is more similar.

### Next step

The next step is to build a small product/store dataset so the project can recommend similar clothing items from stores in Egypt.